// GENERATED by tools/board/extract.mjs — do not edit.
window.FIT_BOARD = {
  "generated": "2026-08-18",
  "modules": [
    {
      "file": "flows/coach/client-groups.html",
      "label": "Client groups",
      "role": "coach",
      "screens": [
        {
          "id": "s-groups",
          "hash": "784751e2ee52",
          "title": "Clients | Groups",
          "inApp": "Clients",
          "status": "shipped",
          "theme": "dark",
          "entry": true,
          "note": "A group is a named set of clients — app accounts and CRM contacts side by side, exactly like the participants of an event (the add-participant endpoint already keys off relationshipId, so both kinds go down one path).",
          "external": [
            "./clients.html#s-client-detail"
          ],
          "shots": [
            {
              "file": "s-groups.webp",
              "label": ""
            },
            {
              "file": "s-groups__empty.webp",
              "label": "No groups yet"
            }
          ],
          "level": 0,
          "order": 0
        },
        {
          "id": "s-group-detail",
          "hash": "bf3fd3013f32",
          "title": "Group detail",
          "inApp": "Morning",
          "status": "shipped",
          "theme": "dark",
          "entry": false,
          "note": "Everything on this screen is a row. The previous pass wrapped each action in a card with a two-line description and each session in another card — ~200px spent on things a coach does daily and already understands. Rebuil",
          "external": [
            "./sessions.html#s-series",
            "./calendar.html",
            "./invite.html?mode=schedule&origin=s-group-detail&filter=group&group=morning"
          ],
          "shots": [
            {
              "file": "s-group-detail.webp",
              "label": ""
            },
            {
              "file": "s-group-detail__editing.webp",
              "label": "Edit mode — tap a row to remove"
            },
            {
              "file": "s-group-detail__no-schedule.webp",
              "label": "Not on any session"
            },
            {
              "file": "s-group-detail__drawer.webp",
              "label": "Schedule drawer — one-off or weekly"
            }
          ],
          "level": 1,
          "order": 0
        },
        {
          "id": "s-group-schedule",
          "hash": "f48c4cfa5981",
          "title": "Group schedule",
          "inApp": "Morning",
          "status": "shipped",
          "theme": "dark",
          "entry": false,
          "note": "Every date this group is on, in one place. Same shape as the series detail in session-detail.html, because the question is the same — when does this run? — only the filter is the group instead of one placement.",
          "external": [
            "./sessions.html#s-series",
            "./calendar.html"
          ],
          "shots": [
            {
              "file": "s-group-schedule.webp",
              "label": ""
            },
            {
              "file": "s-group-schedule__recurring-only.webp",
              "label": "Filtered to recurring"
            }
          ],
          "level": 2,
          "order": 0
        },
        {
          "id": "s-group-smart",
          "hash": "18df7b4a3d2d",
          "title": "Smart group detail",
          "inApp": "Owes money",
          "status": "shipped",
          "theme": "dark",
          "entry": false,
          "note": "Same screen shape as a manual group, minus everything that implies hand-picked membership: no Add, no Edit, no attach-to-series. The note says out loud where the membership comes from and how people leave it.",
          "external": [
            "./clients.html#s-client-detail"
          ],
          "shots": [
            {
              "file": "s-group-smart.webp",
              "label": ""
            }
          ],
          "level": 1,
          "order": 1
        },
        {
          "id": "s-group-create",
          "hash": "50ad3098eee4",
          "title": "Create group",
          "inApp": "New group",
          "status": "shipped",
          "theme": "dark",
          "entry": false,
          "note": "Name + multi-select over all clients. The row component is the one from contact import (imp-) — same checkbox, avatar, tag grammar, so “pick people” looks the same everywhere in the app.",
          "external": [],
          "shots": [
            {
              "file": "s-group-create.webp",
              "label": ""
            }
          ],
          "level": 1,
          "order": 2
        },
        {
          "id": "s-group-rename",
          "hash": "372be2c4c1fa",
          "title": "Rename group",
          "inApp": "Group name",
          "status": "shipped",
          "theme": "dark",
          "entry": false,
          "note": "A pushed screen, not an inline field in the header and not a sheet — and it’s a straight clone of shared/messages.html#s-group-rename, which already solves this exact problem for DM groups.",
          "external": [],
          "shots": [
            {
              "file": "s-group-rename.webp",
              "label": ""
            }
          ],
          "level": 2,
          "order": 1
        },
        {
          "id": "s-add-to-group",
          "hash": "3f5165fa8463",
          "title": "Client → groups",
          "inApp": "Anna’s groups",
          "status": "shipped",
          "theme": "dark",
          "entry": false,
          "note": "Opened from the Add to group pill on the client card. The gap it closes: groups were only visible from the group side, so from a client you couldn’t see — or change — where they belong.",
          "external": [
            "./clients.html#s-client-detail"
          ],
          "shots": [
            {
              "file": "s-add-to-group.webp",
              "label": ""
            }
          ],
          "orphan": true,
          "level": 3,
          "order": 0
        },
        {
          "id": "s-group-add",
          "hash": "baab418a5a0d",
          "title": "Add clients",
          "inApp": "Add to Morning",
          "status": "shipped",
          "theme": "dark",
          "entry": false,
          "note": "Same picker as Create, minus the name field — the group already has a name, and re-asking for it makes the coach wonder whether they’re about to make a second group.",
          "external": [],
          "shots": [
            {
              "file": "s-group-add.webp",
              "label": ""
            }
          ],
          "level": 2,
          "order": 2
        },
        {
          "id": "s-group-chat",
          "hash": "2c81d6492c3c",
          "title": "Group chat",
          "inApp": "Morning",
          "status": "proposal",
          "theme": "dark",
          "entry": false,
          "note": "The group thread from shared/messages.html, unchanged — only the two states that groups introduce are drawn here.",
          "external": [
            "../shared/messages.html#s-group-settings",
            "./invite.html?mode=invite&origin=s-group-chat"
          ],
          "shots": [
            {
              "file": "s-group-chat.webp",
              "label": ""
            }
          ],
          "level": 2,
          "order": 3
        }
      ],
      "edges": [
        {
          "from": "s-groups",
          "to": "s-group-detail",
          "back": false
        },
        {
          "from": "s-groups",
          "to": "s-group-smart",
          "back": false
        },
        {
          "from": "s-groups",
          "to": "s-group-create",
          "back": false
        },
        {
          "from": "s-group-detail",
          "to": "s-groups",
          "back": true
        },
        {
          "from": "s-group-detail",
          "to": "s-group-chat",
          "back": false
        },
        {
          "from": "s-group-detail",
          "to": "s-group-schedule",
          "back": false
        },
        {
          "from": "s-group-detail",
          "to": "s-group-add",
          "back": false
        },
        {
          "from": "s-group-detail",
          "to": "s-group-rename",
          "back": false
        },
        {
          "from": "s-group-schedule",
          "to": "s-group-detail",
          "back": true
        },
        {
          "from": "s-group-smart",
          "to": "s-groups",
          "back": true
        },
        {
          "from": "s-group-create",
          "to": "s-groups",
          "back": true
        },
        {
          "from": "s-group-create",
          "to": "s-group-detail",
          "back": true
        },
        {
          "from": "s-group-rename",
          "to": "s-group-detail",
          "back": true
        },
        {
          "from": "s-add-to-group",
          "to": "s-group-create",
          "back": true
        },
        {
          "from": "s-group-add",
          "to": "s-group-detail",
          "back": true
        },
        {
          "from": "s-group-chat",
          "to": "s-group-detail",
          "back": true
        }
      ]
    }
  ]
};
